image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    pullRequests: true
    pullRequestsFromForks: true
    addBadge: true

tasks:
  - name: Restore
    init: dotnet tool restore && dotnet paket restore && dotnet build

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ionide.ionide-fsharp
